<?php
#database tables
$tbl_admin= 'tbl_admin';
$tbl_log ='tbl_log';
$tbl_etudiant= 'tbl_etudiant';
$tbl_etudiant_cdl= 'tbl_etudiant_cdl';
$tbl_etudiant_pri= 'tbl_etudiant_pri';
$tbl_professeur= 'tbl_professeur';
$tbl_professeur_cdl= 'tbl_professeur_cdl';
$tbl_professeur_pri= 'tbl_professeur_pri';
$tbl_filiere= 'tbl_filiere';
$tbl_filiere_cdl= 'tbl_filiere_cdl';
$tbl_filiere_pri= 'tbl_filiere_pri';
$tbl_groupe= 'tbl_groupe';
$tbl_groupe_cdl='tbl_groupe_cdl';
$tbl_groupe_pri='tbl_groupe_pri';
$tbl_cours= 'tbl_cours';
$tbl_cours_inscription= 'tbl_cours_inscription';
$tbl_cours_cdl= 'tbl_cours_cdl';
$tbl_cours_pri= 'tbl_cours_pri';
$tbl_seance= 'tbl_seance';
$tbl_seance_cdl= 'tbl_seance_cdl';
$tbl_seance_pri= 'tbl_seance_pri';
$tbl_descriptif= 'tbl_descriptif';
$tbl_descriptif_cdl= 'tbl_descriptif_cdl';
$tbl_descriptif_pri= 'tbl_descriptif_pri';
$tbl_syllabus= 'tbl_syllabus';
$tbl_syllabus_cdl= 'tbl_syllabus_cdl';
$tbl_syllabus_pri= 'tbl_syllabus_pri';
$tbl_jours= 'tbl_jours';
$tbl_salle= 'tbl_salle';
$tbl_session= 'tbl_session';
$tbl_horaire= 'tbl_horaire';
$tbl_header= 'tbl_header';
$tbl_footer= 'tbl_footer';
$tbl_emploi_items= 'tbl_emploi_items';
$tbl_inscription_cours= 'tbl_inscription_cours';
$tbl_inscription_cours_cdl= 'tbl_inscription_cours_cdl';
$tbl_inscription_cours_pri= 'tbl_inscription_cours_pri';
$tbl_note= 'tbl_note';
$tbl_note_cdl= 'tbl_note_cdl';
$tbl_note_pri= 'tbl_note_pri';
$tbl_absence= 'tbl_absence';
$tbl_absence_cdl= 'tbl_absence_cdl';
$tbl_absence_pri= 'tbl_absence_pri';
$tbl_buletin= 'tbl_buletin';
$tbl_buletin_data= 'tbl_buletin_data';
$tbl_document= 'tbl_document';
$tbl_actualite= 'tbl_actualite';
$tbl_demande= 'tbl_demande';
$tbl_header= 'tbl_header';
$tbl_footer= 'tbl_footer';
$tbl_livre= 'tbl_livre';
$tbl_empreinte= 'tbl_empreinte';
$tbl_reglement= 'tbl_reglement';
$tbl_paiement='tbl_paiement';
$tbl_paiement_data='tbl_paiement_data';
$tbl_menu='tbl_menu';
$tbl_sondage_data='tbl_sondage_data';
$tbl_sondage='tbl_sondage';
$tbl_titre_emploi='tbl_titre_emploi';
$tbl_emploi_items='tbl_emploi_items';
$tbl_menu_statistic='tbl_menu_statistic';
$tbl_menu_acces='tbl_menu_acces';
$tbl_employeur='tbl_employeur';
$tbl_offre_emploi='tbl_offre_emploi';
$tbl_cv='tbl_cv';
$tbl_reglement='tbl_reglement';
$tbl_admin_menu='tbl_admin_menu';
$tbl_finance='tbl_finance';
#application vars
$docTarget= "../module/document/docs/";
$selected= "selected=\"selected\"";
$checked="checked=\"checked\"";
$non= "<img src=\"../images/delete_x.gif\" border=\"0\" width=\"18\" height=\"18\" />";
$oui= "<img src=\"../images/check_ok.gif\" border=\"0\" width=\"18\" height=\"18\" />";
$targetLogo= "../images/logo/";
$parpage =25;
$idSession=10;
$automne='Fall';
$printemps='Spring';
$ete='Summer';
$maxParClass=25;
 ?>
